#!/bin/sh
#
# NOTE:
# This file will be installed in /config/failover/tgstandby and it will
# be called by /usr/lib/failover/f5tgstandby
#
# - This file is for customer additions for tasks
#   to be performed when failover goes to standby state
#
# - Refer to /usr/lib/failover/f5tgstandby for more information
#
#

